server:
  port: 9001
spring:
  application:
    name: goods
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://192.168.1.104:8066/V_SHOP?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    url: jdbc:mysql://192.168.1.104:3306/v_shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8161/eureka
  instance:
    prefer-ip-address: true